import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Header from "@/components/layout/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {" "}
        <link
          rel="stylesheet"
          href="https://js.arcgis.com/4.24/esri/themes/light/main.css"
        />
      </head>
      <body className={`${inter.className} bg-black dark:bg-black`}>
        <Header />
        <Navbar />

        {children}
      </body>
    </html>
  );
}
